project:
  type: website
  output-dir: docs
  
website:
  title: "NameofYourWebsite"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research
      - href: https://jkbirnir.github.io/GVPT729B/
        text: GVPT729

format:
  html:
    theme: vapor
    css: styles.css
    toc: true

editor: visual


